import { Hero } from './hero';

export const HEROES: Hero[] = [
    { id: 3, name: 'Pragma', details:' is a unique bonded love that matures over many years. It’s an everlasting love between a couple that chooses to put equal effort into their relationship. Commitment and dedication are required to reach “Pragma.” Instead of “falling in love,” you are “standing in love” with the partner you want by your side indefinitely.' },
    { id: 6, name: 'Storge', details:' is a naturally occurring love rooted in parents and children, as well as best friends. It’s an infinite love built upon acceptance and deep emotional connection. This love comes easily and immediately in parent and child relationships.' },
    { id: 9, name: 'Eros', details:' is a primal love that comes as a natural instinct for most people. It’s a passionate love displayed through physical affection. These romantic behaviors include, but are not limited to, kissing, hugging and holding hands. This love is a desire for another person’s physical body.' },
    { id: 12, name: 'Ludus', details:' is a child-like and flirtatious love commonly found in the beginning stages of a relationship (a.k.a. the honeymoon stage). This type of love consists of teasing, playful motives and laughter between two people. Although common in young couples, older couples who strive for this love find a more rewarding relationship.' },
    { id: 15, name: 'Mania', details:' is an obsessive love towards a partner. It leads to unwanted jealousy or possessiveness — known as codependency. Most cases of obsessive love are found in couples with an imbalance of love towards each other. An imbalance of Eros and Ludus is the main cause of Mania. With healthy levels of playful and romantic love, the harm of obsessive love can be avoided.' },
    { id: 18, name: 'Philautia', details:' is a  healthy form of love where you recognize your self-worth and don’t ignore your personal needs. Self-love begins with acknowledging your responsibility for your well-being. It’s challenging to exemplify the outbound types of love because you can’t offer what you don’t have.' },
    { id: 21, name: 'Agape', details:' is the highest level of love to offer. It’s given without any expectations of receiving anything in return. Offering Agape is a decision to spread love in any circumstances — including destructive situations. Agape is not a physical act, it’s a feeling, but acts of self-love can elicit Agape since self-monitoring leads to results.' },
    { id: 24, name: 'Philia', details: ' is love without romantic attraction and occurs between friends or family members. It occurs when both people share the same values and respect each other — it’s commonly referred to as “brotherly love.”'}
  ];